"use server";

import { db } from "@/app/lib/db";
import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({});

export async function generateRoadmap(user_exam_id: number) {
    try {
        // 1️⃣ Fetch user exam
        const userExam = await db.userExam.findUnique({
            where: { id: user_exam_id },
            include: {
                exam: {
                    include: {
                        subjects: {
                            include: {
                                topics: true,
                            },
                        },
                    },
                },
            },
        });

        if (!userExam) {
            throw new Error("UserExam not found");
        }

        const { exam, start_date, end_date } = userExam;

        // 2️⃣ Mark generation started
        await db.userExam.update({
            where: { id: user_exam_id },
            data: {
                roadmap_status: "in_progress",
            },
        });

        // 3️⃣ Build subjects/topics
        const subjects = exam.subjects.map((s: any) => ({
            name: s.name,
            topics: s.topics.map((t: any) => t.name),
        }));

        // 4️⃣ AI Prompt
        const prompt = `
You are an expert academic planner.

Create a study roadmap for the exam "${exam.name} taking context about the exam as ${exam.aiContext} which is out objective".

The roadmap should help a student prepare effectively by breaking down the syllabus into manageable phases, weeks, and tasks.

Preparation duration:
${start_date.toDateString()} to ${end_date.toDateString()}

Subjects and topics:
${subjects
                .map(
                    (s: any) =>
                        `- ${s.name}: ${s.topics.join(", ")}`
                )
                .join("\n")}

Output ONLY valid JSON in this exact structure:

{
  "title": "string",
  "description": "string",
  "summary": "string",
  "phases": [
    {
      "phase_name": "string",
      "description": "string",
      "duration": "string",
      "weeks": [
        {
          "week_number": number,
          "focus": "string",
          "tasks": [
            {
              "title": "string",
              "description": "string",
              "start_date": "YYYY-MM-DD",
              "end_date": "YYYY-MM-DD"
            }
          ]
        }
      ]
    }
  ],
  "milestones": [
    {
      "name": "string",
      "goal": "string",
      "target_date": "YYYY-MM-DD"
    }
  ]
}
`;

        // 5️⃣ Generate roadmap with AI
        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt,
        });

        let textResponse = response.text ?? "";

        // Clean AI response
        const cleanedText = textResponse
            .replace(/```json/i, "")
            .replace(/```/g, "")
            .trim()
            .replace(/,\s*}/g, "}")
            .replace(/,\s*]/g, "]");

        const roadmapData = JSON.parse(cleanedText);

        // 6️⃣ Save everything in TRANSACTION
        const roadmap = await db.$transaction(async (tx) => {

            // Create roadmap
            const createdRoadmap = await tx.roadmap.create({
                data: {
                    user_exam_id,
                    title:
                        roadmapData.title ||
                        `Roadmap for ${exam.name}`,
                    description:
                        roadmapData.description ||
                        "Generated by AI",
                    summary:
                        roadmapData.summary || null,
                    generated_by_ai: true,
                    start_date,
                    end_date,
                },
            });

            // Create phases → weeks → tasks
            if (
                roadmapData.phases &&
                Array.isArray(roadmapData.phases)
            ) {
                for (const [
                    phaseIndex,
                    phase,
                ] of roadmapData.phases.entries()) {

                    const createdPhase =
                        await tx.roadmapPhase.create({
                            data: {
                                roadmap_id:
                                    createdRoadmap.id,
                                phase_name:
                                    phase.phase_name,
                                description:
                                    phase.description ||
                                    null,
                                duration:
                                    phase.duration ||
                                    null,
                                order_index:
                                    phaseIndex,
                            },
                        });

                    // 🔥 PHASE TEST
                    await tx.test.create({
                        data: {
                            title: `${phase.phase_name} Test`,
                            type: "PHASE",

                            description: `Assessment for ${phase.phase_name}`,

                            userExamId: user_exam_id,

                            phaseId: createdPhase.id,

                            totalMarks: 100,

                            duration: 120,

                            isGenerated: false,
                        },
                    });

                    if (
                        phase.weeks &&
                        Array.isArray(phase.weeks)
                    ) {
                        for (const [
                            weekIndex,
                            week,
                        ] of phase.weeks.entries()) {

                            const createdWeek =
                                await tx.roadmapWeek.create({
                                    data: {
                                        phase_id:
                                            createdPhase.id,
                                        week_number:
                                            week.week_number ||
                                            weekIndex + 1,
                                        focus:
                                            week.focus ||
                                            null,
                                        order_index:
                                            weekIndex,
                                    },
                                });

                            // 🔥 WEEKLY TEST
                            await tx.test.create({
                                data: {
                                    title: `Week ${createdWeek.week_number} Test`,
                                    type: "WEEKLY",

                                    description: `Assessment for Week ${createdWeek.week_number}`,

                                    userExamId: user_exam_id,

                                    weekId: createdWeek.id,

                                    totalMarks: 50,

                                    duration: 60,

                                    isGenerated: false,
                                },
                            });

                            // Tasks
                            if (
                                week.tasks &&
                                Array.isArray(
                                    week.tasks
                                )
                            ) {
                                await tx.roadmapTask.createMany({
                                    data:
                                        week.tasks.map(
                                            (
                                                task: any,
                                                taskIndex: number
                                            ) => ({
                                                week_id:
                                                    createdWeek.id,
                                                title:
                                                    task.title,
                                                description:
                                                    task.description ||
                                                    null,
                                                start_date:
                                                    task.start_date
                                                        ? new Date(
                                                            task.start_date
                                                        )
                                                        : null,
                                                end_date:
                                                    task.end_date
                                                        ? new Date(
                                                            task.end_date
                                                        )
                                                        : null,
                                                order_index:
                                                    taskIndex,
                                            })
                                        ),
                                });
                            }
                        }
                    }
                }
            }

            // Milestones
            if (
                roadmapData.milestones &&
                Array.isArray(
                    roadmapData.milestones
                )
            ) {
                await tx.milestone.createMany({
                    data:
                        roadmapData.milestones.map(
                            (m: any) => ({
                                roadmap_id:
                                    createdRoadmap.id,
                                name: m.name,
                                goal: m.goal || null,
                                target_date:
                                    m.target_date
                                        ? new Date(
                                            m.target_date
                                        )
                                        : null,
                            })
                        ),
                });
            }

            // 🔥 FINAL TESTS
            await tx.test.createMany({
                data: [
                    {
                        title: "Final Revision Test 1",
                        type: "FINAL",

                        description:
                            "Covers earlier roadmap phases and weeks",

                        userExamId: user_exam_id,

                        totalMarks: 150,

                        duration: 180,

                        nOfFinalTests: 1,

                        isGenerated: false,
                    },

                    {
                        title: "Final Revision Test 2",
                        type: "FINAL",

                        description:
                            "Intermediate full syllabus assessment",

                        userExamId: user_exam_id,

                        totalMarks: 200,

                        duration: 240,

                        nOfFinalTests: 2,

                        isGenerated: false,
                    },

                    {
                        title: "Final Grand Mock Test",
                        type: "FINAL",

                        description:
                            "Complete exam simulation",

                        userExamId: user_exam_id,

                        totalMarks: 300,

                        duration: 300,

                        nOfFinalTests: 3,

                        isGenerated: false,
                    },
                ],
            });

            return createdRoadmap;
        }, {
            timeout: 60000 // 60 seconds
        });

        // 7️⃣ Mark completed
        await db.userExam.update({
            where: { id: user_exam_id },
            data: {
                roadmap_status: "completed",
            },
        });

        // 8️⃣ Notification
        await db.notification.create({
            data: {
                user_id: userExam.user_id,
                message: `Your roadmap for ${exam.name} has been generated successfully!`,
            },
        });

        return {
            success: true,
            roadmap_id: roadmap.id,
        };

    } catch (err: any) {
        console.error(
            "❌ Roadmap generation failed:",
            err
        );

        await db.userExam.update({
            where: { id: user_exam_id },
            data: {
                roadmap_status: "failed",
            },
        });

        return {
            success: false,
            message:
                err.message ||
                "Roadmap generation failed",
        };
    }
}